storage.c: Fix compiler error due to missing writev() declaration
storage.c:90:7: error: implicit declaration of function ‘writev’; did you mean ‘write’? [-Werror=implicit-function-declaration]
   90 |  rc = writev(g_out_fd, iov, ARRAY_SIZE(iov));
      |       ^~~~~~
      |       write